// Background orchestrator: runs the debate loop across chat tabs.
//
// Flow:
//   1. Round 1: every debater tab receives the user's idea independently.
//   2. Rounds 2..N: each debater receives the OTHER debaters' previous
//      answers and is asked to critique and revise.
//   3. Early stop (optional): the judge is asked "AGREE or DISAGREE" after
//      each round; AGREE ends the debate.
//   4. Final: the judge tab receives all final answers and must produce a
//      structured framework verdict, which also lands in the judge's chat.
//   5. The verdict is saved as framework.md via the Downloads API
//      (semi-automation handoff for Antigravity).

importScripts("prompts.js");

// ---------------- tab messaging ----------------

async function sendAndWait(tabId, prompt, timeoutMs) {
  return new Promise((resolve) => {
    chrome.tabs.sendMessage(tabId, { type: "SEND_AND_WAIT", prompt, timeoutMs }, (res) => {
      if (chrome.runtime.lastError) {
        resolve({ ok: false, error: chrome.runtime.lastError.message });
      } else {
        resolve(res || { ok: false, error: "no response from tab" });
      }
    });
  });
}

async function ping(tabId) {
  return new Promise((resolve) => {
    chrome.tabs.sendMessage(tabId, { type: "PING" }, (res) => {
      resolve(!chrome.runtime.lastError && res && res.ok ? res : null);
    });
  });
}

// ---------------- debate engine ----------------

let running = false;

async function runDebate(config) {
  if (running) throw new Error("A debate is already running.");
  running = true;
  const log = [];
  const report = (line) => {
    log.push(line);
    chrome.runtime.sendMessage({ type: "PROGRESS", line, log }).catch(() => {});
  };

  try {
    const debaters = config.debaters;       // [{tabId, name}]
    const judge = config.judge;             // {tabId, name}
    const maxRounds = config.maxRounds || 3;
    const earlyStop = !!config.earlyStop;
    const adversarial = !!config.adversarial;
    if (adversarial && debaters.length >= 2) debaters[debaters.length - 1].adversarial = true;

    // answers[tabId] = latest answer text from that tab
    const answers = {};

    for (let round = 1; round <= maxRounds; round++) {
      report(`--- Round ${round}/${maxRounds} ---`);
      for (const d of debaters) {
        let prompt;
        if (round === 1) {
          prompt = config.idea;
        } else {
          prompt = buildDebatePrompt(round, config.idea,
            othersBlock(debaters, answers, d.tabId), d.adversarial);
        }
        report(`Sending to ${d.name}...`);
        const res = await sendAndWait(d.tabId, prompt, config.timeoutMs);
        if (!res.ok) throw new Error(`${d.name}: ${res.error}`);
        answers[d.tabId] = res.text;
        report(`${d.name} answered (${res.text.length} chars).`);
      }

      if (earlyStop && round < maxRounds && judge) {
        report(`Asking ${judge.name} if models agree...`);
        const agreeRes = await sendAndWait(
          judge.tabId,
          JUDGE_AGREE_PROMPT +
            debaters.map(d => `--- ${d.name} ---\n${answers[d.tabId]}`).join("\n\n"),
          config.timeoutMs
        );
        if (agreeRes.ok && /^AGREE\b/i.test(agreeRes.text.trim())) {
          report(`${judge.name} says AGREE — stopping early after round ${round}.`);
          break;
        }
        report(agreeRes.ok
          ? `${judge.name} says DISAGREE — continuing.`
          : "Agreement check failed, continuing.");
      }
    }

    // Final judgment — the verdict is also written into the judge's own chat
    const userIdeaBlock = `The user's original idea was:\n${config.idea}\n\n`;
    report(`Requesting final framework from ${judge.name}...`);
    const verdict = await sendAndWait(judge.tabId,
      JUDGE_FINAL_PROMPT + userIdeaBlock + judgeTranscript(debaters, answers),
      config.timeoutMs);
    if (!verdict.ok) throw new Error(`Judge ${judge.name}: ${verdict.error}`);

    const md = buildFrameworkMd(config, log, verdict.text);
    await saveFile("framework.md", md);
    report("Done. framework.md saved to your Downloads folder (move it into your project for Antigravity).");
    return { ok: true, log };
  } finally {
    running = false;
  }
}

function buildFrameworkMd(config, log, verdictText) {
  const stamp = new Date().toISOString().replace(":", "-");
  return (
    `# Project Framework — generated by AI Council\n\n` +
    `- Date: ${new Date().toISOString()}\n` +
    `- Debaters: ${config.debaters.map(d => d.name).join(", ")}\n` +
    `- Judge: ${config.judge.name}\n` +
    `- Rounds: ${config.maxRounds}\n\n` +
    `## Original Idea\n\n${config.idea}\n\n` +
    `## Judge Verdict\n\n${verdictText}\n\n` +
    `---\n\n<!-- session: ${stamp} -->\n`
  );
}

function saveFile(filename, text) {
  return new Promise((resolve, reject) => {
    const dataUrl = "data:text/markdown;charset=utf-8," + encodeURIComponent(text);
    chrome.downloads.download(
      { url: dataUrl, filename: `ai-council/${filename}`, saveAs: false },
      (id) => (chrome.runtime.lastError ? reject(new Error(chrome.runtime.lastError.message)) : resolve(id))
    );
  });
}

// Re-run the debate on an Antigravity question: takes question text,
// debates it the same way, saves question.txt with the judge's answer.
async function runQuestion(config) {
  const result = await runDebate({
    ...config,
    idea:
      "A coding agent (Antigravity) hit this problem while building the project:\n\n" +
      config.idea +
      "\n\nDiagnose the root cause and propose the fix."
  });
  return result;
}

chrome.runtime.onMessage.addListener((msg, _sender, sendResponse) => {
  if (msg.type === "START_DEBATE") {
    runDebate(msg.config)
      .then(r => sendResponse(r))
      .catch(e => sendResponse({ ok: false, error: String(e.message || e) }));
    return true;
  }
  if (msg.type === "START_QUESTION") {
    runQuestion(msg.config)
      .then(r => sendResponse(r))
      .catch(e => sendResponse({ ok: false, error: String(e.message || e) }));
    return true;
  }
});
